language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
matrix:
  fast_finish: true
dist: xenial
services:
  - xvfb
install:
  - pip install -r requirements.txt
  - buildout
before_script:
- firefox -v
script:
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - brian.duncan@wildcardcorp.com
